// <auto-generated />
using System;
using GYM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GYM.Data.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20260720210101_InitialSetup")]
    partial class InitialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GYM.Data.Entities.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConditionValue")
                        .HasColumnType("int");

                    b.Property<string>("Condition_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConditionValue = 0,
                            Condition_type = "workouts_completed",
                            Description = "Complete your first workout",
                            Icon = "fa-trophy",
                            Name = "Newbie",
                            Points = 5
                        },
                        new
                        {
                            Id = 2,
                            ConditionValue = 0,
                            Condition_type = "miles_runned",
                            Description = "Run 5 miles",
                            Icon = "fa-star",
                            Name = "Rocky Balboa",
                            Points = 10
                        },
                        new
                        {
                            Id = 3,
                            ConditionValue = 0,
                            Condition_type = "workouts_completed",
                            Description = "Complete 5 workouts",
                            Icon = "fa-Medal",
                            Name = "Killer machine!",
                            Points = 30
                        });
                });

            modelBuilder.Entity("GYM.Data.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExerciseTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("GYM.Data.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<string>("VisualReferenceUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Flexiones estándar manteniendo la espalda recta.",
                            Name = "Flexiones de Pecho",
                            Reps = 15,
                            Sets = 4,
                            VisualReferenceUrl = "https://example.com/pushups.gif"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sentadillas libres bajando a 90 grados.",
                            Name = "Sentadillas",
                            Reps = 20,
                            Sets = 4,
                            VisualReferenceUrl = "https://example.com/squats.gif"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Levantamiento controlado de pesas para bíceps.",
                            Name = "Curl de Biceps con Mancuerna",
                            Reps = 12,
                            Sets = 3,
                            VisualReferenceUrl = "https://example.com/biceps.gif"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Mantener la postura isométrica para fuerza de core.",
                            Name = "Plancha Abdominal",
                            Reps = 1,
                            Sets = 3,
                            VisualReferenceUrl = "https://example.com/plank.gif"
                        });
                });

            modelBuilder.Entity("GYM.Data.Entities.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateOnly>("MeasureAt")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("MileRun")
                        .HasColumnType("time");

                    b.Property<decimal>("Strength")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("GYM.Data.Entities.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly>("EstimatedTime")
                        .HasColumnType("time");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrainingName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Place")
                        .HasDatabaseName("IX_Trainings_Place");

                    b.ToTable("Trainings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 250,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rutina básica ideal para iniciar en casa sin equipo pesado.",
                            Difficulty = "Fácil",
                            EstimatedTime = new TimeOnly(0, 30, 0),
                            Place = "Home",
                            TrainingName = "Rutina Full Body Principiantes"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 400,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Entrenamiento enfocado en aumentar volumen y fuerza muscular.",
                            Difficulty = "Intermedio",
                            EstimatedTime = new TimeOnly(0, 45, 0),
                            Place = "GYM",
                            TrainingName = "Fuerza e Hipertrofia de Brazos"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 600,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Entrenamiento de alta intensidad al aire libre para quemar grasa.",
                            Difficulty = "Avanzado",
                            EstimatedTime = new TimeOnly(1, 0, 0),
                            Place = "Outdoors",
                            TrainingName = "Desafío Cardio & Core Exterior"
                        });
                });

            modelBuilder.Entity("GYM.Data.Entities.TrainingExercises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TrainingId");

                    b.ToTable("TrainingExercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 1,
                            TrainingId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 2,
                            TrainingId = 1
                        },
                        new
                        {
                            Id = 3,
                            ExerciseId = 1,
                            TrainingId = 2
                        },
                        new
                        {
                            Id = 4,
                            ExerciseId = 3,
                            TrainingId = 2
                        },
                        new
                        {
                            Id = 5,
                            ExerciseId = 2,
                            TrainingId = 3
                        },
                        new
                        {
                            Id = 6,
                            ExerciseId = 4,
                            TrainingId = 3
                        });
                });

            modelBuilder.Entity("GYM.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "aranda.castillo.miguel@gmail.com",
                            Password = "hola123",
                            Phone = "6645709069",
                            Role = "User"
                        },
                        new
                        {
                            Id = 2,
                            Email = "trainer@example.com",
                            Password = "juan123",
                            Phone = "8885748622",
                            Role = "Trainer"
                        });
                });

            modelBuilder.Entity("GYM.Data.Entities.UserDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 0,
                            Gender = "Male",
                            JoinAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Miguel Angel",
                            Surname = "Aranda Castillo",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 0,
                            Gender = "Male",
                            JoinAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Juan",
                            Surname = "Jimenez Ortega",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("GYM.Data.Entities.User_Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Completed_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("GYM.Data.Entities.Booking", b =>
                {
                    b.HasOne("GYM.Data.Entities.Training", "Training")
                        .WithMany("Bookings")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GYM.Data.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GYM.Data.Entities.Statistic", b =>
                {
                    b.HasOne("GYM.Data.Entities.User", "User")
                        .WithMany("Statistics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GYM.Data.Entities.TrainingExercises", b =>
                {
                    b.HasOne("GYM.Data.Entities.Exercise", "Exercise")
                        .WithMany("TrainingExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GYM.Data.Entities.Training", "Training")
                        .WithMany("TrainingExercises")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("GYM.Data.Entities.UserDetail", b =>
                {
                    b.HasOne("GYM.Data.Entities.User", "User")
                        .WithOne("UserDetail")
                        .HasForeignKey("GYM.Data.Entities.UserDetail", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GYM.Data.Entities.User_Achievement", b =>
                {
                    b.HasOne("GYM.Data.Entities.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GYM.Data.Entities.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GYM.Data.Entities.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("GYM.Data.Entities.Exercise", b =>
                {
                    b.Navigation("TrainingExercises");
                });

            modelBuilder.Entity("GYM.Data.Entities.Training", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("TrainingExercises");
                });

            modelBuilder.Entity("GYM.Data.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Statistics");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
