// <auto-generated />
using System;
using GYM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GYM.Data.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20260725072015_InitialSetup")]
    partial class InitialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GYM.Data.Entities.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConditionValue")
                        .HasColumnType("int");

                    b.Property<string>("Condition_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConditionValue = 0,
                            Condition_type = "workouts_completed",
                            Description = "Complete your first workout",
                            Icon = "fa-trophy",
                            Name = "Newbie",
                            Points = 5
                        },
                        new
                        {
                            Id = 2,
                            ConditionValue = 0,
                            Condition_type = "miles_runned",
                            Description = "Run 5 miles",
                            Icon = "fa-star",
                            Name = "Rocky Balboa",
                            Points = 10
                        },
                        new
                        {
                            Id = 3,
                            ConditionValue = 0,
                            Condition_type = "stats_completed_1",
                            Description = "Your first measures",
                            Icon = "fa-Medal",
                            Name = "First Stats",
                            Points = 30
                        });
                });

            modelBuilder.Entity("GYM.Data.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DoneAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExerciseTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("GYM.Data.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<string>("VisualReferenceUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Perform a standard push-up while keeping your back straight and lowering your chest toward the floor.",
                            Name = "Push-Ups",
                            Reps = 15,
                            Sets = 4,
                            VisualReferenceUrl = "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMmhqd250ZHlqNjM1eThyZzJnbXFva3czc21hZmptOTZteTN0ZjA2eSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3pY8FQP9uMtDKXkYqX/giphy.gif"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Perform a squat by lowering your hips toward the floor while keeping your chest up and your back straight.",
                            Name = "Bodyweight Squats",
                            Reps = 20,
                            Sets = 4,
                            VisualReferenceUrl = "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYmx4cmJxOGZwMHUwaXBrbmJqaW9sa3ZlYmU3eGNsYXZpbTR6c2ppcCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/fnmk65werlZFy81pGw/giphy.gif"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Curl dumbbells upward toward your shoulders while keeping your elbows close to your body and controlling the movement.",
                            Name = "Dumbbell Bicep Curls",
                            Reps = 12,
                            Sets = 3,
                            VisualReferenceUrl = "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3YTQydzBwZnZxZXlweGt2NmxrbXFydGQ1MjFmdXYwZjZza3YwNnB2diZlcD12MV9naWZzX3NlYXJjaCZjdD1n/kFnaSyOxFVVKFVOi9O/giphy.gif"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Hold a straight-body position supported by your forearms and toes while keeping your core tight.",
                            Name = "Plank",
                            Reps = 1,
                            Sets = 3,
                            VisualReferenceUrl = "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZm44bmI1eGs1d2RnbmNxb2I5ajJtMXF4NGd4MmNnc3NpMWJvOXQwdCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/KbOsMppYjfO5a/giphy.gif"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Step forward with one leg and lower your hips until both knees are bent, then return to the starting position and alternate legs.",
                            Name = "Alternating Lunges",
                            Reps = 12,
                            Sets = 3,
                            VisualReferenceUrl = "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbzdmMTg5d2tyaHY3eW92MHhja2ZhdzczN3Zra21lMmk1bWNyNTc5MSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/l3q2Q3sUEkEyDvfPO/giphy.gif"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Press dumbbells upward from shoulder level until your arms are extended, then lower them under control.",
                            Name = "Dumbbell Shoulder Press",
                            Reps = 10,
                            Sets = 3,
                            VisualReferenceUrl = "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMmJ5ZmdrdmJmNzZtZDMxeHo3cTlrcW1zMXZtbWhpeHJud2V3NDUwNyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/s1zHoMpAKEPnKoqW8k/giphy.gif"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Lie on your back with your knees bent and lift your hips upward while squeezing your glutes.",
                            Name = "Glute Bridges",
                            Reps = 15,
                            Sets = 4,
                            VisualReferenceUrl = "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMmVwM3JhdWlma2gyZTNtY2czNzFsZG50ODhyYnExdHc2cGVnNWV0aiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/oOGc4pXsX22XjE2eTA/giphy.gif"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Start in a plank position and alternate driving your knees toward your chest while keeping your core engaged.",
                            Name = "Mountain Climbers",
                            Reps = 20,
                            Sets = 3,
                            VisualReferenceUrl = "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeTVhbWxjdTloN3c0cWw1YWFwOW9jczV5cXlmZDFlN2xiOWdnZ2U0MCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/VzlPEkuoqlgjehxvxk/giphy.gif"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Pull a dumbbell toward your torso while keeping your back straight and your elbow close to your body.",
                            Name = "Dumbbell Rows",
                            Reps = 12,
                            Sets = 3,
                            VisualReferenceUrl = "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExem52cXIxMDJ6bzdmNTk2d3o3YXZrNjY3MGozZW8zM2F5N3E2NW1pdCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3oEjHM9hzerMdVjYWI/giphy.gif"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Raise your heels off the ground while balancing on the balls of your feet, then slowly lower your heels.",
                            Name = "Standing Calf Raises",
                            Reps = 20,
                            Sets = 4,
                            VisualReferenceUrl = "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3eHdqY2l2aDhiOTBuZjh5OHc1YTV5dzdhb29yd2hhaDJodnRhdnpzcyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/4VYaL0JOguZrBgjQOt/giphy.gif"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Normal run",
                            Name = "Run",
                            Reps = 45,
                            Sets = 1,
                            VisualReferenceUrl = "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ3p1YnNkeHBkczN3b2c3emkxcTQ2cTFlY3NlazdhdGdrNTY5c2E4byZlcD12MV9naWZzX3NlYXJjaCZjdD1n/CUbiYQbsKSGAM/giphy.gif"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Several sprints and rest in between.",
                            Name = "Sprint",
                            Reps = 10,
                            Sets = 3,
                            VisualReferenceUrl = "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNWY4c2V4YWw5MDYzNTM3YW12dWJ0NjlxbGt4ZndpZ201eWJoamNhdyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/VFwqlu33Ob5ELrRXiw/giphy.gif"
                        });
                });

            modelBuilder.Entity("GYM.Data.Entities.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateOnly>("MeasureAt")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("MileRun")
                        .HasColumnType("time");

                    b.Property<decimal>("Strength")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("GYM.Data.Entities.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly>("EstimatedTime")
                        .HasColumnType("time");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrainingName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Place")
                        .HasDatabaseName("IX_Trainings_Place");

                    b.ToTable("Trainings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 250,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A beginner-friendly full-body workout that can be performed at home with little to no equipment.",
                            Difficulty = "Easy",
                            EstimatedTime = new TimeOnly(0, 30, 0),
                            Place = "Home",
                            TrainingName = "Beginner Full Body Workout"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 400,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A strength-focused workout targeting the chest, shoulders, back, and arms using dumbbells and bodyweight exercises.",
                            Difficulty = "Intermediate",
                            EstimatedTime = new TimeOnly(0, 45, 0),
                            Place = "GYM",
                            TrainingName = "Upper Body Strength Workout"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 600,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A high-intensity workout combining cardio and core exercises to improve endurance and burn calories.",
                            Difficulty = "Advanced",
                            EstimatedTime = new TimeOnly(1, 0, 0),
                            Place = "Outdoors",
                            TrainingName = "High Intensity Cardio & Core"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 450,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A lower-body focused workout designed to strengthen the legs and glutes using a combination of bodyweight and weighted exercises.",
                            Difficulty = "Intermediate",
                            EstimatedTime = new TimeOnly(0, 50, 0),
                            Place = "GYM",
                            TrainingName = "Lower Body Strength & Glutes"
                        },
                        new
                        {
                            Id = 5,
                            Calories = 300,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cardio full of runs and sprints to archive a better physical condition.",
                            Difficulty = "Intermediate",
                            EstimatedTime = new TimeOnly(1, 15, 0),
                            Place = "Outdoors",
                            TrainingName = "Full Cardio"
                        });
                });

            modelBuilder.Entity("GYM.Data.Entities.TrainingExercises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TrainingId");

                    b.ToTable("TrainingExercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExerciseId = 1,
                            TrainingId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExerciseId = 2,
                            TrainingId = 1
                        },
                        new
                        {
                            Id = 3,
                            ExerciseId = 4,
                            TrainingId = 1
                        },
                        new
                        {
                            Id = 4,
                            ExerciseId = 8,
                            TrainingId = 1
                        },
                        new
                        {
                            Id = 5,
                            ExerciseId = 11,
                            TrainingId = 1
                        },
                        new
                        {
                            Id = 6,
                            ExerciseId = 1,
                            TrainingId = 2
                        },
                        new
                        {
                            Id = 7,
                            ExerciseId = 3,
                            TrainingId = 2
                        },
                        new
                        {
                            Id = 8,
                            ExerciseId = 6,
                            TrainingId = 2
                        },
                        new
                        {
                            Id = 10,
                            ExerciseId = 4,
                            TrainingId = 3
                        },
                        new
                        {
                            Id = 11,
                            ExerciseId = 7,
                            TrainingId = 3
                        },
                        new
                        {
                            Id = 12,
                            ExerciseId = 8,
                            TrainingId = 3
                        },
                        new
                        {
                            Id = 13,
                            ExerciseId = 11,
                            TrainingId = 3
                        },
                        new
                        {
                            Id = 14,
                            ExerciseId = 12,
                            TrainingId = 3
                        },
                        new
                        {
                            Id = 15,
                            ExerciseId = 2,
                            TrainingId = 4
                        },
                        new
                        {
                            Id = 16,
                            ExerciseId = 5,
                            TrainingId = 4
                        },
                        new
                        {
                            Id = 17,
                            ExerciseId = 7,
                            TrainingId = 4
                        },
                        new
                        {
                            Id = 18,
                            ExerciseId = 10,
                            TrainingId = 4
                        },
                        new
                        {
                            Id = 19,
                            ExerciseId = 5,
                            TrainingId = 4
                        },
                        new
                        {
                            Id = 20,
                            ExerciseId = 11,
                            TrainingId = 5
                        },
                        new
                        {
                            Id = 21,
                            ExerciseId = 12,
                            TrainingId = 5
                        });
                });

            modelBuilder.Entity("GYM.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GYM.Data.Entities.UserDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("GYM.Data.Entities.User_Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Completed_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("GYM.Data.Entities.Booking", b =>
                {
                    b.HasOne("GYM.Data.Entities.Training", "Training")
                        .WithMany("Bookings")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GYM.Data.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GYM.Data.Entities.Statistic", b =>
                {
                    b.HasOne("GYM.Data.Entities.User", "User")
                        .WithMany("Statistics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GYM.Data.Entities.TrainingExercises", b =>
                {
                    b.HasOne("GYM.Data.Entities.Exercise", "Exercise")
                        .WithMany("TrainingExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GYM.Data.Entities.Training", "Training")
                        .WithMany("TrainingExercises")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("GYM.Data.Entities.UserDetail", b =>
                {
                    b.HasOne("GYM.Data.Entities.User", "User")
                        .WithOne("UserDetail")
                        .HasForeignKey("GYM.Data.Entities.UserDetail", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GYM.Data.Entities.User_Achievement", b =>
                {
                    b.HasOne("GYM.Data.Entities.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GYM.Data.Entities.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GYM.Data.Entities.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("GYM.Data.Entities.Exercise", b =>
                {
                    b.Navigation("TrainingExercises");
                });

            modelBuilder.Entity("GYM.Data.Entities.Training", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("TrainingExercises");
                });

            modelBuilder.Entity("GYM.Data.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Statistics");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
